vim.api.nvim_set_keymap("n", "<c-h>", ":FocusSplitLeft<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<c-j>", ":FocusSplitDown<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<c-k>", ":FocusSplitUp<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<c-l>", ":FocusSplitRight<CR>", { silent = true })
vim.keymap.set("n", "<leader>mn", "<cmd>FocusToggle<cr>", { silent = true })
vim.keymap.set("n", "<leader>mm", "<cmd>FocusMaximise<cr>", { silent = true })
vim.keymap.set("n", "<leader>me", "<cmd>FocusEqualise<cr>", { silent = true })
